// dashboardData.js
export const kpiCards = [
  {
    title: '25M',
    subtitle: 'Clicks',
    icon: 'TrendingUp',
    bgColor: 'bg-orange-100',
    iconColor: 'text-orange-600',
  },
  {
    title: '380M',
    subtitle: 'Impressions',
    icon: 'Eye',
    bgColor: 'bg-green-100',
    iconColor: 'text-green-600',
    highlighted: true,
  },
  {
    title: '165k',
    subtitle: 'Leads',
    icon: 'Users',
    bgColor: 'bg-red-100',
    iconColor: 'text-red-600',
  },
  {
    title: '₹950,00,000',
    subtitle: 'Amount Spent',
    icon: 'DollarSign',
    bgColor: 'bg-purple-100',
    iconColor: 'text-purple-600',
  },
  {
    title: '₹580,00,000',
    subtitle: 'Remaining Amount',
    icon: 'CreditCard',
    bgColor: 'bg-cyan-100',
    iconColor: 'text-cyan-600',
  },
];

export const campaignData = [
  { name: 'Awareness Campaign', status: 'Active', key: 'awareness' },
  { name: 'Lead Campaign', status: 'Active', key: 'lead' },
  { name: 'Engagement Campaign', status: 'Active', key: 'engagement' },
];

export const userCampaigns = [
  {
    userName: 'Praveen Dubey',
    id: '124580757687852',
    campaignName: 'Lead generation campaign',
    type: 'Awareness',
    delivery: 'Active',
    budget: '₹ 600.00',
    budgetType: 'Daily',
    reach: '152,230',
    impressions: '452,003',
    results: '1600',
    resultType: 'Website Visit',
  },
  {
    userName: 'Saleem Javed',
    id: '124580757687852',
    campaignName: 'Leads Leap',
    type: 'Post Engagement',
    delivery: 'Not Delivering',
    deliveryNote: 'Ad set Inactive',
    budget: '₹ 270.00',
    budgetType: 'Daily',
    reach: '73,010',
    impressions: '124,489',
    results: '810',
    resultType: 'Links clicks',
  },
  {
    userName: 'Abhishek Gupta',
    id: '124580757687852',
    campaignName: 'Product Launches',
    type: 'Post Engagement',
    delivery: 'Completed',
    budget: '₹ 350.00',
    budgetType: 'Daily',
    reach: '10,340',
    impressions: '45,731',
    results: '3200',
    resultType: 'Post Engagement',
  },
  {
    userName: 'Rohit Sahu',
    id: '124580757687852',
    campaignName: 'Event Excite',
    type: 'Awareness',
    delivery: 'Inactive',
    budget: '₹ 175.00',
    budgetType: 'Daily',
    reach: '7500',
    impressions: '25,188',
    results: '—',
    resultType: 'Landing Page View',
  },
  {
    userName: 'Siddharth Sharma',
    id: '124580757687852',
    campaignName: 'Discover & Explore',
    type: 'Leads',
    delivery: 'Ad Set Off',
    budget: '₹ 500.00',
    budgetType: 'Daily',
    reach: '145,520',
    impressions: '678,910',
    results: '235',
    resultType: 'Landing Page View',
  },
];

export const paymentHistory = [
  {
    userName: 'Praveen Dubey',
    handle: '@praveendubey',
    transactionId: '124580757687852',
    date: '27 Feb, 2024',
    mode: 'Wallet',
    amount: '₹ 6,000.00',
    status: 'Completed',
  },
  {
    userName: 'Praveen Dubey',
    handle: '@praveendubey',
    transactionId: '124580757687852',
    date: '27 Feb, 2024',
    mode: 'Net Banking',
    amount: '₹ 25,000.00',
    status: 'Failed',
  },
  {
    userName: 'Praveen Dubey',
    handle: '@praveendubey',
    transactionId: '124580757687852',
    date: '27 Feb, 2024',
    mode: 'UPI',
    amount: '₹ 15,000.00',
    status: 'Completed',
  },
  {
    userName: 'Praveen Dubey',
    handle: '@praveendubey',
    transactionId: '124580757687852',
    date: '27 Feb, 2024',
    mode: 'Wallet',
    amount: '₹ 10,000.00',
    status: 'Completed',
  },
];

export const chartData = [
  { date: '1 Feb', value: 100 },
  { date: '2 Feb', value: 250 },
  { date: '3 Feb', value: 350 },
  { date: '4 Feb', value: 250 },
  { date: '5 Feb', value: 300 },
  { date: '6 Feb', value: 500 },
  { date: '7 Feb', value: 450 },
];